### PR TITLE
Openh264 2.1.1

### PR DESCRIPTION
**Pull request by nanonyme**
Update to 2.1.1. There was a breaking ABI change so soname was bumped.

https://phabricator.endlessm.com/T29880

### CODE REVIEW

**Comment by nanonyme** [comment]
@wjt created new PR since Cisco just made the release 2.1.1.

**Comment by wjt** [comment]
Ok to test

**Comment by nanonyme** [comment]
Any chance to get this handled forward? We're going to take this commit into use in freedesktop-sdk soon.

**Comment by wjt** [comment]
On the Endless side, we'll need to adjust `debian/` for the soname bump.

**Comment by nanonyme** [comment]
I see. The changes look otherwise quite straightforward but I'm not entirely sure what you expect changelog to contain.

**Comment by nanonyme** [comment]
I pushed WIP commit that should contain relevant packaging changes. If someone can amend it and create changelog, that would be great.

**Comment by wjt** [comment]
retest this please! thank you kindly robot

**Comment by wjt** [comment]
Thanks, I added a changelog entry (forging your signature) and pushed a `Version_2.1.1` tag https://github.com/endlessm/noopenh264/tree/Version_2.1.1 to placate our build infrastructure.

@andrunko our Chromium links against this so would want to be rebuilt against the new version. I guess the best way to deal with that is just to land a new Chromium right after this? :-)

**Review by andrunko — APPROVED** [review]
Changes lgtm - not merging just yet but I will follow up on it tomorrow before merging the new chromium 83 update.

**Pull request merged**
