### PR TITLE
Update for openh264 2.2.0

### PR DESCRIPTION
**Pull request by nanonyme**
There were no changes to API headers

### CODE REVIEW

**Comment by nanonyme** [comment]
@dbnicholson can you please review?

**Comment by mcatanzaro** [comment]
Maybe @wjt could help move this along?

**Comment by wjt** [comment]
ok to test

**Comment by wjt** [comment]
What is the practical need for this change – does a library that links to openh264 have a versioned dependency on this version?

**Comment by nanonyme** [comment]
Sort of. Various parties like ffmpeg and relevant gstreamer plugin build the version into themselves and refuse to initialize openh264 without exact version match.

**Comment by wjt** [comment]
OK, so we will need to rebuild the gst plugin (the only thing we have in the os itself). Thanks!

In the meantime I found https://gitlab.com/freedesktop-sdk/openh264-extension/-/merge_requests/31 and https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1419 which were helpful.

**Pull request merged**
