### PR TITLE
Update to openh264 2.0.0

### PR DESCRIPTION
**Pull request by Othko97**
openh264 has had a new release which breaks API and ABI. This updates the headers and structs to match the new version.

It also updates the `meson.build`, which has not been done yet upstream.

https://phabricator.endlessm.com/T27705

### CODE REVIEW

**Comment by ramcq** [comment]
ok to test

**Comment by ramcq** [comment]
@Othko97 This is a bit daft but, can you push a tag to your repo for me? Our CI needs it to determine the Debian package version because it's a bit special.

```
ramcq@xi:~/endless/noopenh264$ git tag Version_2.0.0 84161c3a7e166ef244fb59e6bd7e7c9b1e9d2d14
ramcq@xi:~/endless/noopenh264$ git push --tags coldtom HEAD:coldtom/update
Total 0 (delta 0), reused 0 (delta 0)
To github.com:Othko97/noopenh264.git
 ! [remote rejected] Version_2.0.0 -> Version_2.0.0 (permission denied)
error: failed to push some refs to 'git@github.com:Othko97/noopenh264.git'
```

**Comment by ramcq** [comment]
retest this please

**Comment by AdrianVovk** [comment]
What's the status of this?

**Review by andrunko — APPROVED** [review]
lgtm, thanks for the changes.

**Pull request merged**
