### PR TITLE
codec_ver.h: Sync for 2.3.0

### PR DESCRIPTION
**Pull request by alatiera**

### CODE REVIEW

**Comment by alatiera** [comment]
(Still testing)

**Comment by nanonyme** [comment]
I think you should sync all other headers too assuming I failed the sync.

**Comment by alatiera** [comment]
Indeed, will take a look on monday for the rest

**Comment by nanonyme** [comment]
It would actually be really cool if these version consistencies could be verified here. I still think freedesktop-sdk needs more advanced tests since it's the primary gate before which g-b-m and Flathub will not break.

**Comment by jjardon** [comment]
Seems this is missing:
```
diff --git a/codec/api/svc/codec_app_def.h b/codec/api/svc/codec_app_def.h
index bb3c3d6..9b13c33 100644
--- a/codec/api/svc/codec_app_def.h
+++ b/codec/api/svc/codec_app_def.h
@@ -589,7 +589,9 @@ typedef struct TagEncParamExt {
   bool    bEnableFrameCroppingFlag;    ///< enable frame cropping flag: TRUE always in application
   bool    bEnableSceneChangeDetect;
 
-  bool    bIsLosslessLink;            ///<  LTR advanced setting
+  bool    bIsLosslessLink;             ///< LTR advanced setting
+  bool    bFixRCOverShoot;             ///< fix rate control overshooting
+  int     iIdrBitrateRatio;            ///< the target bits of IDR is (idr_bitrate_ratio/100) * average target bit per frame.
 } SEncParamExt;
 
 /**
```

**Comment by nanonyme** [comment]
That looks like possible ABI issue.

**Comment by nanonyme** [comment]
It's not as such problem for noopenh264 but if there's struct size changes, there can be segfaults with real OpenH264.

**Comment by mcatanzaro** [comment]
> It's not as such problem for noopenh264 but if there's struct size changes, there can be segfaults with real OpenH264.

Yeah that is not acceptable. It means the 2.3.0 update is broken and should not be used. Drat.

It's frustrating that (a) this is not the first time this has happened, and (b) it has taken several weeks to notice due to slowness updating both GNOME and Fedora.

**Comment by nanonyme** [comment]
> > It's not as such problem for noopenh264 but if there's struct size changes, there can be segfaults with real OpenH264.
> 
> Yeah that is not acceptable. It means the 2.3.0 update is broken and should not be used. Drat.
> 
> It's frustrating that (a) this is not the first time this has happened, and (b) it has taken several weeks to notice due to slowness updating both GNOME and Fedora.

Many things went wrong. I think we're now at least capable of updating OpenH264 without runtime release. We need better automation and I think this copying headers strategy isn't scaling well. Note, there probably isn't really crash because version change prevents initializing new incompatible library.

**Comment by mcatanzaro** [comment]
> Note, there probably isn't really crash because version change prevents initializing new incompatible library.

That's true for GStreamer, but this struct is used in [lots of other places](https://codesearch.debian.net/search?q=SEncParamExt&literal=1&perpkg=1).

**Comment by nanonyme** [comment]
Let's not merge this. Let's instead revert the 2.3.0 version bump as it was done incorrectly. For 2.2.0 headers need to be fixed to have correct version.

**Comment by alatiera** [comment]
Closing in favor of #11

**Pull request closed without merging**
